### ISSUE TITLE
Class 'diselop\ztree\ZTree' not found

### ISSUE THREAD

**Issue by sjjliqpl** [diselop/yii2-ztree#1]
First of all, thank you for sharing your code.When I use yii2-tree extensions, my IDE reminded me that there is a class called ZTree(Inside Ztree.php document is defined as).At that time when I used this class, but the application returns an error (such as title).When I check where the error is, I find Ztree.php really defines ZTree instead Ztree.So I suggest you change the class name or the file name.

**Comment by diselop** [comment]
Thanks for issue. If i can be honest, then i have forgot this project. Because i had made this project for my needs. I'm going to modifying it.
